### ISSUE TITLE
Add informative error logging to debug Treasury report failures

### ISSUE THREAD

**Issue by as1729** [usdigitalresponse/usdr-gost#2525]
### Why is this issue important?

When treasury reports fail there is not much contextual information added to the logs to easily identify:
1. Which files or source-data is causing the issue?
2. Which users are impacted?

### Current State

When an error occurs in the arpa treasury report generation we see generic information of the stack trace and system-generated error message as seen by [this trace](https://app.datadoghq.com/apm/trace/5887620889693993296?colorBy=service&env=production&graphType=flamegraph&shouldShowLegend=true&sort=time&spanID=5887620889693993296&spanViewType=metadata&timeHint=1706307550391.034&view=spans).
For example:
```
Error: Unsupported ZIP Compression method NaN
    at parse_local_file (/app/node_modules/xlsx/xlsx.js:2688:18)
    at parse_zip (/app/node_modules/xlsx/xlsx.js:2649:3)
    at parse (/app/node_modules/xlsx/xlsx.js:1485:47)
    at Object.read (/app/node_modules/xlsx/xlsx.js:1817:9)
    at zip_read (/app/node_modules/xlsx/xlsx.js:3434:43)
    at read_zip (/app/node_modules/xlsx/xlsx.js:23643:8)
    at readSync (/app/node_modules/xlsx/xlsx.js:23715:69)
    at Object.readFileSync (/app/node_modules/xlsx/xlsx.js:23738:9)
    at loadTemplate (/app/src/arpa_reporter/services/get-template.js:49:27)
    at getTemplate (/app/src/arpa_reporter/services/get-template.js:62:28)
```

### Expected State

When an error occurs in the arpa treasury report generation we see:
1. Stack trace (which already exists today)
2. Input-data (filename) that caused the error to occur (or filename that caused the issue)

For Example:
```
Error: Unsupported ZIP Compression method NaN. Please review contents of filename: "projectBulkUpload.csv"
```

Note: this additional information should only be logged in case of an error. We do not need logging for every single upload/file that is being iterated on for aggregation.

### Implementation Plan

The following functions need to be added...

**Comment by jasonzhang4628** [comment]
taking this on!

**Comment by ClaireValdivia** [comment]
this is out of date and we had already adding some tracking here, closing out.
