### ISSUE TITLE
docker-compose up fails: Error: Could not find any Python installation to use

### ISSUE THREAD

**Issue by NatHillardUSDR** [usdigitalresponse/usdr-gost#781]
On current `_staging`, if you run `docker compose up --build`, you get the below error:

```
...
 => ERROR [usdr-gost-frontend app_base 7/7] RUN ["yarn", "run", "setup"]                                                           39.4s 
------                                                                                                                                   
 > [usdr-gost-frontend app_base 7/7] RUN ["yarn", "run", "setup"]:                                                                       
#0 0.455 yarn run v1.22.17                                                                                                               
#0 0.504 $ yarn install && yarn run bootstrap                                                                                            
#0 0.763 [1/5] Validating package.json...                                                                                                
#0 0.772 [2/5] Resolving packages...                                                                                                     
#0 1.234 [3/5] Fetching packages...
#0 24.82 [4/5] Linking dependencies...
#0 37.25 [5/5] Building fresh packages...
#0 38.30 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
#0 38.30 error /app/node_modules/@parcel/watcher: Command failed.
#0 38.30 Exit code: 1
#0 38.30 Command: node-gyp-build
#0 38.30 Arguments: 
#0 38.30 Directory: /app/node_modules/@parcel/watcher
#0 38.30 Output:
#0 38.30 gyp info it worked if it ends with ok
#0 38.30 gyp info using node-gyp@9.1.0
#0 38.30 gyp info using node@16.14.0 | linux | arm64
#0 38.30 gyp ERR! find Python 
#0 38.30 gyp ERR! find Python Python is not set from command line or npm configuration
#0 38.30 gyp ERR! find Python Python is not set from environment variable PYTHON
#0 38.30 gyp ERR! find Python checking if "python3" can be used
#0 38.30 gyp ERR! find Python - "python3" is not in PATH or produced an error
#0 38.30 gyp ERR! find Python checking if "python" can be used
#0 38.30 gyp ERR! find Python - "python" is not in PATH or produced an error
#0 38.30 gyp ERR! find Python 
#0 38.30 gyp ERR! find Python **********************************************************
#0 38.30 gyp ERR! find Python You need to install the latest version of Python.
#0 38.30 gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
#0 38.30 gyp ERR! find Python you can try one of the following options:
#0 38.30 gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
#0 38.30 gyp ERR! find Python   (accepted by both node-gyp and npm)
#0 38.30 gyp ERR! find Python - Set the environment variable PYTHON
#0 38.30 gyp ERR! find Python - Set the npm configuration variable python:
#0 38.30 gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
#0 38.30 gyp ERR! find Python For more information consult the documentation at:
#0 38.30 gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
#0 38.30 gyp ERR! find Python **********************************************************
#0 38.30 gyp ERR! find Python 
#0 38.30 gyp ERR! configure error 
#0 38.30 gyp ERR! stack Error: Could not find any Python installation to use
#0 38.30 gyp ERR! stack     at PythonFinder.fail (/app/node_modules/node-gyp/lib/find-python.js:330:47)
#0 38.30 gyp ERR! stack     at PythonFinder.runChecks (/app/node_modules/node-gyp/lib/find-python.js:159:21)
#0 38.30 gyp ERR! stack     at PythonFinder.<anonymous> (/app/node_modules/node-gyp/lib/find-python.js:202:16)
#0 38.30 gyp ERR! stack     at PythonFinder.execFileCallback (/app/node_modules/node-gyp/lib/find-python.js:294:16)
#0 38.30 gyp ERR! stack     at exithandler (node:child_process:406:5)
#0 38.30 gyp ERR! stack     at ChildProcess.errorhandler (node:child_process:418:5)
#0 38.30 gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
#0 38.30 gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
#0 38.30 gyp ERR! stack     at onErrorNT (node:internal/child_process:478:16)
#0 38.30 gyp ERR! stack     at processTicksAndRejections (node:internal/process/task_queues:83:21)
#0 38.30 gyp ERR! System Linux 5.15.49-linuxkit
#0 38.30 gyp ERR! command "/usr/local/bin/node" "/app/node_modules/.bin/node-gyp" "rebuild"
#0 38.30 gyp ERR! cwd /app/node_modules/@parcel/watcher
#0 38.30 gyp ERR! node -v v16.14.0
#0 38.30 gyp ERR! node-gyp -v v9.1.0
#0 38.30 gyp ERR! not ok
#0 38.94 error Command failed with exit code 1.
#0 38.94 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
failed to solve: executor failed running [yarn run setup]: exit code: 1
```

The image is missing several dependencies.

**Comment by LieAlbertTriAdrian** [comment]
@NatHillardUSDR There's no python binary in alpine and node-gyp requires it to be built. One of the possible solutions is adding the related python binary during `apk add` like this draft PR https://github.com/usdigitalresponse/usdr-gost/pull/787

Another way is to just use the non-alpine version of the image but the size of the docker container might dramatically increase, which is not ideal

**Comment by NatHillardUSDR** [comment]
Jinx! I left a further clarifying comment over in the PR [here](https://github.com/usdigitalresponse/usdr-gost/pull/782#issuecomment-1377662394) as well along the same lines, actually at roughly the time you posted your comment.

The dependencies go:
```
npm ls node-gyp-build 
cares-grant-opportunities@1.0.0 /Users/nhillard/Documents/Code/USDR/usdr-gost
└─┬ lerna@5.6.2
  └─┬ nx@14.8.3
    └─┬ @parcel/watcher@2.0.4
      └── node-gyp-build@4.5.0
```
Potentially the real problem here though is that `lerna` arguably shouldn't be required at build time (or, maybe at all?) for this repo -- I don't believe we're using the local inter-package dependencies that [lerna-boostrap](https://github.com/lerna/lerna/tree/main/commands/bootstrap) allows for.

**Comment by NatHillardUSDR** [comment]
This will be made obsolete by #928  -- closing it out
